
fn main() -> Result<(), Box<std::error::Error>> {
    println!("Hello!");

    Ok(())
}
